version: "2.4"

volumes:
  mariadb-backups-data: {}

services:
  mariadb:
    image: mariadb:10
    volumes:
      - "./test/testdb-init.sql:/docker-entrypoint-initdb.d/testdb-init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=my-secret-pw --execute "USE testdb;"'
      interval: 4s
      timeout: 20s
      retries: 100

  automysqlbackup:
    build: .
    volumes:
      - "mariadb-backups-data:/backup"
    environment:
      USERNAME: root
      PASSWORD: "my-secret-pw"
      DBHOST: mariadb
      DBEXCLUDE: "performance_schema information_schema"
      IGNORE_TABLES: "testdb.ignoretable"
      EXTRA_OPTS: "--single-transaction"
    depends_on:
      mariadb:
        condition: service_healthy
    command: bash -c "rm -rf /backup/* && automysqlbackup"

  sut:
    build: ./test
    volumes:
      - "mariadb-backups-data:/backup"
    depends_on:
      - automysqlbackup
    command: bash -c "wait_to_finish.sh automysqlbackup && bats /usr/local/bin/automysqlbackup.bats"
